### ISSUE TITLE
Исправления

### ISSUE THREAD

**Issue by Fasturtle1** [KSAviX/example1vue#1]
- [x] Не надо оборачивать всю страницу в `v-data-table`. Это сама таблица. Сделай шапку отдельно от таблицы, это избавит тебя от большинства проблем с версткой.  
 - [x] Выровнять чекбокс "Показать уволенных" по вертикали относительно центра кнопок(см. пример)  
 - [x] Сделать отступы между кнопками меньше(см. пример)  
![image](https://user-images.githubusercontent.com/35260551/64350730-30e3da00-d00a-11e9-8ec6-6a607f09f481.png)  
 - [x] Данные колонок "Дата увольнения", "Ставка", "База", "Аванс" и "Почасовая" центрировать по горизонтали  
 - [x] Даты в колонках "Дата приёма" и "Дата увольнения" привести в правильный формат дат(дд.мм.гггг)  
 - [x] Исправить ошибку в названии колонки "Дата **уольнения**"  
 - [x] Если открыть диалог редактирования при клике по строке в колонке "Ставка" и кликнуть **вне** диалога что бы он закрылся, то для этой строки таблицы больше не получится открыть этот диалог.  
 - [x] Сверстать диалоги редактирования как в примере(зеленые кнопочки без теней(проп `text`))   
 - [x] Количество введенных символов в строках ввода не отображать.  
 - [x] При нажатии кнопки "Выбрать все" в углу таблицы выбираются, видимо, и уволенные сотрудники. Выбрано одно поле, но текст кнопки сменился на "Снять с должностей"  

Если возникнут вопросы, пиши.

**Comment by KSAviX** [comment]
Что-то пока не понимаю как стиль для компонента писать

**Comment by Fasturtle1** [comment]
Привет, вот ссылка с якорем на твой вопрос:  
https://vuejs.org/v2/guide/class-and-style.html#With-Components  
Сразу письмо не увидел, вот 89026581777 мой номер, добавь в телеграмме.  Напиши там.
